export { ARMOR_INSPECT, ARMOR_LAYERS } from './config';
export { describeHit } from './lib/hit-report';
export type { HitLayer, HitReport } from './lib/hit-report';
export { useArmorInspect } from './model/context';
export type { ArmorLayerKey } from './model/context';
export { ArmorInspectPanel } from './ui/ArmorInspectPanel';
export { ArmorInspectProvider } from './ui/ArmorInspectProvider';
export type { ArmorInspectProviderProps } from './ui/ArmorInspectProvider';
export { ArmorLegend } from './ui/ArmorLegend';
export { HitReadout } from './ui/HitReadout';
export type { HitReadoutProps } from './ui/HitReadout';
