export const API_ERROR_CODES = [
  'INTERNAL_ERROR',
  'VALIDATION_FAILED',
  'UNAUTHORIZED',
  'FORBIDDEN',
  'NOT_FOUND',
  'CONFLICT',
  'RATE_LIMITED',

  'PLAYER_NOT_FOUND',
  'CLAN_NOT_FOUND',
  'TANK_NOT_FOUND',
  'ARMOR_MODEL_NOT_FOUND',
  'LESTA_UNAVAILABLE',
  'LESTA_ACCOUNT_HIDDEN',

  'API_KEY_INVALID',
  'API_KEY_REVOKED',
  'PLAN_LIMIT_REACHED',

  'MOD_DEVICE_INVALID',
  'MOD_SIGNATURE_INVALID',
  'BIND_CODE_INVALID',

  'GOAL_CLOSED',

  'PAYMENT_REQUIRED',
  'PAYMENT_FAILED',
  'SUBSCRIPTION_REQUIRED',
  'CHECKOUT_UNAVAILABLE',
  'INTEGRATION_UNAVAILABLE',
  'TRIAL_UNAVAILABLE',
  'PROMO_INVALID',
  'PROMO_EXPIRED',
  'PROMO_EXHAUSTED',
  'PROMO_ALREADY_REDEEMED',
  'PROMO_CHECKOUT_ONLY',
  'PROMO_REDEEM_ONLY',

  'REPLAY_INVALID',
  'REPLAY_DUPLICATE',

  'STREAMER_SLUG_TAKEN',
  'STREAMER_CHANNEL_TAKEN'
] as const;
