import { STREAMER_SETTINGS } from '@otmetki/schemas';

export const SETTINGS_FIELDS = [
  { path: 'display.resolution', group: 'display', kind: 'text', placeholder: '1920x1080' },
  { path: 'display.refreshRate', group: 'display', kind: 'number', min: 30, max: 540, step: 1, unit: 'hz' },
  { path: 'display.windowMode', group: 'display', kind: 'enum', options: STREAMER_SETTINGS.windowModes },
  { path: 'display.client', group: 'display', kind: 'enum', options: STREAMER_SETTINGS.clients },
  { path: 'display.preset', group: 'display', kind: 'enum', options: STREAMER_SETTINGS.presets },
  { path: 'display.fpsCap', group: 'display', kind: 'number', min: 0, max: 1000, step: 1, unit: 'fps' },
  { path: 'display.vsync', group: 'display', kind: 'boolean' },
  { path: 'display.tripleBuffering', group: 'display', kind: 'boolean' },
  { path: 'camera.fov', group: 'camera', kind: 'number', min: STREAMER_SETTINGS.fov.min, max: STREAMER_SETTINGS.fov.max, step: 1, unit: 'deg' },
  { path: 'camera.postMortem', group: 'camera', kind: 'boolean' },
  { path: 'camera.sniperDynamicCamera', group: 'camera', kind: 'boolean' },
  { path: 'camera.horizontalStabilisation', group: 'camera', kind: 'boolean' },
  { path: 'controls.sensitivity.arcade', group: 'controls', kind: 'number', min: 0.01, max: 1.5, step: 0.01 },
  { path: 'controls.sensitivity.sniper', group: 'controls', kind: 'number', min: 0.01, max: 1.5, step: 0.01 },
  { path: 'controls.sensitivity.artillery', group: 'controls', kind: 'number', min: 0.01, max: 3, step: 0.01 },
  { path: 'controls.invert', group: 'controls', kind: 'boolean' },
  { path: 'zoom.steps', group: 'zoom', kind: 'multi', options: STREAMER_SETTINGS.zoomSteps },
  { path: 'sight.arcade.reticle', group: 'sight', kind: 'text' },
  { path: 'sight.arcade.gunMarker', group: 'sight', kind: 'enum', options: STREAMER_SETTINGS.gunMarkers },
  { path: 'sight.arcade.colour', group: 'sight', kind: 'text' },
  { path: 'sight.sniper.reticle', group: 'sight', kind: 'text' },
  { path: 'sight.sniper.gunMarker', group: 'sight', kind: 'enum', options: STREAMER_SETTINGS.gunMarkers },
  { path: 'sight.sniper.colour', group: 'sight', kind: 'text' },
  { path: 'markers.enemy.base', group: 'markers', kind: 'multi', options: STREAMER_SETTINGS.markerFields },
  { path: 'markers.enemy.alt', group: 'markers', kind: 'multi', options: STREAMER_SETTINGS.markerFields },
  { path: 'markers.ally.base', group: 'markers', kind: 'multi', options: STREAMER_SETTINGS.markerFields },
  { path: 'markers.ally.alt', group: 'markers', kind: 'multi', options: STREAMER_SETTINGS.markerFields },
  { path: 'markers.destroyed.base', group: 'markers', kind: 'multi', options: STREAMER_SETTINGS.markerFields },
  { path: 'minimap.size', group: 'minimap', kind: 'number', min: 0, max: 10, step: 1 },
  { path: 'minimap.transparency', group: 'minimap', kind: 'number', min: 0, max: 100, step: 1, unit: 'percent' },
  { path: 'minimap.viewRangeCircles', group: 'minimap', kind: 'boolean' },
  { path: 'minimap.drawRangeCircle', group: 'minimap', kind: 'boolean' },
  { path: 'minimap.spgFireSector', group: 'minimap', kind: 'boolean' },
  { path: 'sound.master', group: 'sound', kind: 'number', min: 0, max: 100, step: 1, unit: 'percent' },
  { path: 'sound.music', group: 'sound', kind: 'number', min: 0, max: 100, step: 1, unit: 'percent' },
  { path: 'sound.effects', group: 'sound', kind: 'number', min: 0, max: 100, step: 1, unit: 'percent' },
  { path: 'sound.voice', group: 'sound', kind: 'number', min: 0, max: 100, step: 1, unit: 'percent' },
  { path: 'sound.sixthSenseSound', group: 'sound', kind: 'text' },
  { path: 'sound.voicePack', group: 'sound', kind: 'text' },
  { path: 'battleUi.damagePanel', group: 'battleUi', kind: 'text' },
  { path: 'battleUi.damageLog', group: 'battleUi', kind: 'boolean' },
  { path: 'battleUi.efficiencyRibbons', group: 'battleUi', kind: 'boolean' },
  { path: 'battleUi.sixthSenseIcon', group: 'battleUi', kind: 'text' },
  { path: 'hardware.cpu', group: 'hardware', kind: 'text' },
  { path: 'hardware.gpu', group: 'hardware', kind: 'text' },
  { path: 'hardware.ramGb', group: 'hardware', kind: 'number', min: 1, max: 1024, step: 1, unit: 'gb' },
  { path: 'hardware.monitor', group: 'hardware', kind: 'text' },
  { path: 'hardware.mouse', group: 'hardware', kind: 'text' },
  { path: 'hardware.mouseDpi', group: 'hardware', kind: 'number', min: 100, max: 50_000, step: 50 },
  { path: 'hardware.pollingHz', group: 'hardware', kind: 'number', min: 100, max: 8000, step: 1, unit: 'hz' },
  { path: 'hardware.pad', group: 'hardware', kind: 'text' },
  { path: 'hardware.keyboard', group: 'hardware', kind: 'text' },
  { path: 'hardware.headset', group: 'hardware', kind: 'text' },
  { path: 'mods.kind', group: 'mods', kind: 'enum', options: STREAMER_SETTINGS.modsKinds },
  { path: 'mods.preset', group: 'mods', kind: 'text' }
] as const;

export const SETTINGS_FORMAT = {
  sensitivityDigits: 2,
  listSeparator: ', ',
  missing: '—'
} as const;
