export { KEY_SPECS, TANK_SPEC_GROUPS, TANK_SPEC_KEYS, TANK_SPECS } from './config';
export type { TankSpecGroup, TankSpecKey, TankSpecMeta, TankSpecUnit } from './config';
export { isLowerBetter, specBest, specDelta } from './lib/spec-rank';
export type { SpecVerdict } from './lib/spec-rank';
export { vehicleIdentity } from './lib/vehicle-identity';
export { specKeyOfPath, specPath, specsOfFlat, specsOfStats } from './lib/vehicle-specs';
export { useSpecFormat } from './model/hooks';
export type { TankIdentityData, TankSpecs } from './model/tank.types';
export { TankCard } from './ui/TankCard';
export type { TankCardProps } from './ui/TankCard';
export { TankCell } from './ui/TankCell';
export type { TankCellProps } from './ui/TankCell';
export { TankIdentity } from './ui/TankIdentity';
export type { TankIdentityProps } from './ui/TankIdentity';
export { WinRateCell } from './ui/WinRateCell';
export type { WinRateCellProps } from './ui/WinRateCell';
export { TankImage } from '@/ui-kit';
export type { TankImageProps, TankImageSize } from '@/ui-kit';
