export {
  achievementsRarityControllerLeaderboardOptions,
  achievementsRarityControllerListOptions,
  achievementsRarityControllerTankRarityOptions,
  eventsControllerDropsOptions,
  leaderboardsControllerOfficialHistoryOptions,
  leaderboardsControllerOfficialNeighborsOptions,
  leaderboardsControllerOfficialTopOptions,
  playersControllerAchievementsOptions,
  playersControllerCareerOptions,
  playersControllerModesOptions,
  playersControllerOfficialRatingsOptions,
  shopControllerArchiveOptions,
  shopControllerListBonusCodesOptions,
  shopControllerListBonusCodesQueryKey,
  shopControllerListNewsInfiniteOptions,
  shopControllerListNewsOptions,
  shopControllerListOffersInfiniteOptions,
  supertestControllerListOptions,
  supertestControllerMineOptions
} from '../generated/@tanstack/react-query.gen';
