export const PROTOCOL = {
  version: 1,
  commands: [
    'ready',
    'close',
    'set',
    'set_many',
    'action',
    'language',
    'bind',
    'open',
    'profile_save',
    'profile_load',
    'profile_rename',
    'profile_delete',
    'profile_export',
    'profile_import',
    'hud_edit',
    'hud_move',
    'hud_reset',
    'hud_reset_all',
    'window_layout'
  ],
  groups: ['data', 'hangar', 'battle'],
  sections: ['battle', 'hangar', 'marks', 'replays', 'streamer', 'data'],
  contexts: ['hangar', 'battle', 'any'],
  pages: ['battle', 'hangar', 'marks', 'replays', 'streamer', 'data', 'profiles', 'hud'],
  alignX: ['left', 'center', 'right'],
  alignY: ['top', 'center', 'bottom'],
  noticeKinds: ['info', 'error', 'code'],
  figureTones: ['pen', 'crit', 'blocked', 'ricochet', 'nodamage'],
  autoLanguage: 'auto'
} as const;
