export const NICKNAME_WORDS = {
  adjectives: [
    'Dark',
    'Silent',
    'Iron',
    'Steel',
    'Red',
    'Black',
    'Crazy',
    'Mad',
    'Lucky',
    'Angry',
    'Wild',
    'Cold',
    'Grey',
    'Old',
    'Lone',
    'Fast',
    'Brave',
    'Shadow',
    'Ghost',
    'Night',
    'Frost',
    'Storm',
    'Toxic',
    'Tiny',
    'Big',
    'Evil',
    'Holy',
    'Sly',
    'Happy',
    'Lazy',
    'Heavy',
    'Rusty',
    'Sneaky',
    'Deadly',
    'Mystic',
    'Royal',
    'Noble',
    'Grim',
    'Hard',
    'Smart',
    'Drunk',
    'Sleepy',
    'Furious',
    'Hungry',
    'Proud',
    'Bold'
  ],
  nouns: [
    'Wolf',
    'Tiger',
    'Bear',
    'Fox',
    'Hunter',
    'Sniper',
    'Tanker',
    'Rider',
    'Driver',
    'Gunner',
    'Hawk',
    'Eagle',
    'Raven',
    'Viper',
    'Cobra',
    'Panther',
    'Dragon',
    'Knight',
    'Soldier',
    'Warrior',
    'Ranger',
    'Rhino',
    'Badger',
    'Lynx',
    'Falcon',
    'Reaper',
    'Pilot',
    'Major',
    'Sergeant',
    'Captain',
    'Commander',
    'Baron',
    'Duke',
    'Cat',
    'Owl',
    'Shark',
    'Bull',
    'Beast',
    'Ace',
    'Joker',
    'Hammer',
    'Anvil',
    'Bullet'
  ],
  russian: [
    'Tankist',
    'Nagibator',
    'Bronya',
    'Shturm',
    'Kotik',
    'Vodila',
    'Medved',
    'Volk',
    'Lis',
    'Yozhik',
    'Mehvod',
    'Navodchik',
    'Komandir',
    'Batya',
    'Kombat',
    'Starshina',
    'Praporshik',
    'Serzhant',
    'Snayper',
    'Tyazhelovoz',
    'Artovod',
    'Svetlyak',
    'Partizan',
    'Bogatyr',
    'Ded',
    'Krot',
    'Zhuk',
    'Kaban',
    'Sokol',
    'Berkut',
    'Grom',
    'Molniya',
    'Taiga',
    'Sibiryak',
    'Ural',
    'Volga',
    'Kuban',
    'Baikal',
    'Pulya',
    'Snaryad',
    'Tapok',
    'Olen',
    'Zayac',
    'Barsuk',
    'Kolobok',
    'Shaman',
    'Kazak',
    'Dembel',
    'Kurs',
    'Gusli',
    'Pelmen'
  ],
  names: [
    'Sanya',
    'Sasha',
    'Dimon',
    'Dima',
    'Vovan',
    'Vova',
    'Lyoha',
    'Lesha',
    'Serega',
    'Seryoga',
    'Andryuha',
    'Kolyan',
    'Tolyan',
    'Zhenya',
    'Misha',
    'Mishka',
    'Ivan',
    'Vanya',
    'Petya',
    'Kostya',
    'Max',
    'Maks',
    'Artem',
    'Artyom',
    'Egor',
    'Yegor',
    'Pasha',
    'Denis',
    'Roma',
    'Ilya',
    'Nikita',
    'Kirill',
    'Oleg',
    'Igor',
    'Vitya',
    'Stas',
    'Slava',
    'Anton',
    'Grisha',
    'Fedya',
    'Vadim',
    'Ruslan',
    'Timur',
    'Artur',
    'Gleb',
    'Yura',
    'Sergey',
    'Aleksey',
    'Dmitriy',
    'Nikolay',
    'Andrey',
    'Vladimir',
    'Evgeniy',
    'Valera',
    'Zhora',
    'Kesha',
    'Tyoma'
  ],
  surnames: [
    'Ivanov',
    'Petrov',
    'Smirnov',
    'Kuznetsov',
    'Popov',
    'Volkov',
    'Sokolov',
    'Lebedev',
    'Kozlov',
    'Novikov',
    'Morozov',
    'Pavlov',
    'Semenov',
    'Golubev',
    'Vinogradov',
    'Bogdanov',
    'Vorobyov',
    'Fedorov',
    'Mikhaylov',
    'Belyaev',
    'Tarasov',
    'Belov',
    'Komarov',
    'Orlov',
    'Kiselev',
    'Makarov',
    'Andreev',
    'Kovalev',
    'Ilyin',
    'Gusev',
    'Titov',
    'Kuzmin',
    'Kudryavtsev',
    'Baranov',
    'Kulikov',
    'Alekseev',
    'Stepanov',
    'Yakovlev',
    'Sorokin',
    'Sergeev',
    'Romanov',
    'Zakharov',
    'Borisov',
    'Korolev',
    'Gerasimov',
    'Ponomarev',
    'Grigoryev',
    'Lazarev',
    'Ershov',
    'Nikitin',
    'Sobolev',
    'Ryabov',
    'Polyakov',
    'Tsvetkov',
    'Danilov',
    'Zhukov',
    'Frolov',
    'Zhuravlev',
    'Nikolaev',
    'Krylov',
    'Maksimov',
    'Sidorov',
    'Osipov',
    'Belousov',
    'Fedotov',
    'Dorofeev',
    'Egorov',
    'Matveev',
    'Bobrov'
  ],
  cities: [
    'msk',
    'spb',
    'ekb',
    'nsk',
    'kzn',
    'krd',
    'nn',
    'samara',
    'omsk',
    'perm',
    'ufa',
    'rnd',
    'vrn',
    'tula',
    'tver',
    'chel',
    'krsk',
    'irk',
    'vlad',
    'tmn',
    'minsk',
    'brest'
  ],
  tanks: [
    'IS7',
    'T62A',
    'Obj140',
    'KV1',
    'T34',
    'Maus',
    'Tiger',
    'Panther',
    'E100',
    'Leo',
    'Strv',
    'Kran',
    'Grille',
    'Batchat',
    'Jagdpanther',
    'Hellcat',
    'Sherman',
    'Patton',
    'KV2',
    'ST1',
    'Object'
  ],
  suffixes: ['RUS', 'Pro', 'X', 'TV', 'YT', 'official', 'real', 'best', 'top', 'boss', 'rus', 'ru', 'go', 'ok', 'play', 'gamer'],
  mash: ['qwerty', 'asdf', 'zxc', 'qwe', 'zzz', 'xxx', 'lol', 'omg', 'nub', 'noob', 'raki', 'rak', 'bot', 'afk']
} as const;

export const NICKNAME_PATTERN_WEIGHTS = {
  adjectiveNoun: 16,
  nameSurname: 16,
  nameYear: 14,
  russian: 13,
  surnameDigits: 8,
  tank: 8,
  decorated: 5,
  caps: 5,
  mash: 7,
  leet: 4,
  nameCity: 4
} as const;

export const NICKNAME_RULES = {
  minLength: 3,
  maxLength: 24,
  birthYears: [1968, 2011],
  leet: { a: '4', e: '3', i: '1', o: '0', s: '5', t: '7' }
} as const;

export const CLAN_WORDS = {
  ruAdjectives: [
    'Стальные',
    'Железные',
    'Красные',
    'Чёрные',
    'Северные',
    'Бронированные',
    'Дикие',
    'Ночные',
    'Бешеные',
    'Свинцовые',
    'Огненные',
    'Серые',
    'Суровые',
    'Сибирские',
    'Уральские',
    'Бравые',
    'Весёлые',
    'Ледяные',
    'Лесные',
    'Степные',
    'Старые',
    'Злые',
    'Тихие',
    'Вольные'
  ],
  ruNouns: [
    'Волки',
    'Медведи',
    'Ястребы',
    'Тигры',
    'Кроты',
    'Коты',
    'Танкисты',
    'Гусары',
    'Партизаны',
    'Демоны',
    'Викинги',
    'Драконы',
    'Самураи',
    'Рыцари',
    'Барсуки',
    'Ёжики',
    'Лоси',
    'Соколы',
    'Кабаны',
    'Мехводы',
    'Бронепоезд',
    'Дембеля',
    'Казаки',
    'Сапёры'
  ],
  ruTemplates: ['Орден «{0}»', 'Братство {1}', 'Отряд «{0}»', 'Батальон «{0}»', 'Легион {1}', 'Академия {1}', 'Гвардия {1}', 'Штаб «{0}»'],
  ruSingles: [
    'Гром',
    'Буря',
    'Рассвет',
    'Тайфун',
    'Прорыв',
    'Рубеж',
    'Кулак',
    'Молот',
    'Клинок',
    'Щит',
    'Бастион',
    'Вихрь',
    'Форпост',
    'Застава',
    'Полигон',
    'Гараж',
    'Рейд',
    'Резерв',
    'Смена',
    'Плацдарм'
  ],
  ruGenitive: ['Стали', 'Брони', 'Огня', 'Севера', 'Урала', 'Тайги', 'Степи', 'Грома', 'Ветра', 'Чести', 'Славы', 'Удачи'],
  enAdjectives: ['Iron', 'Steel', 'Black', 'Red', 'Dark', 'Silent', 'Heavy', 'Wild', 'Frozen', 'Royal', 'Rusty', 'Crimson', 'Northern', 'Lucky'],
  enNouns: [
    'Legion',
    'Wolves',
    'Order',
    'Storm',
    'Hunters',
    'Brotherhood',
    'Crew',
    'Squad',
    'Guard',
    'Pack',
    'Vanguard',
    'Division',
    'Company',
    'Raiders'
  ],
  academy: ['Академия', 'Academy', 'Резерв', 'Школа'],
  colors: [
    '#B80F0A',
    '#E3A30C',
    '#1B5E20',
    '#0D47A1',
    '#4A148C',
    '#263238',
    '#BF360C',
    '#006064',
    '#827717',
    '#3E2723',
    '#880E4F',
    '#33691E',
    '#01579B',
    '#F57F17',
    '#5D4037',
    '#37474F',
    '#C62828',
    '#2E7D32',
    '#1565C0',
    '#6A1B9A'
  ]
} as const;

export const CLAN_PHRASES = {
  mottos: [
    'Вместе — сила!',
    'Ни шагу назад',
    'Играем в удовольствие',
    'Только вперёд',
    'Броня крепка, и танки наши быстры',
    'Тихо пришли — тихо ушли',
    'Лучше меньше, да лучше',
    'Сначала думай, потом стреляй',
    'Нас мало, но мы в танках',
    'Фарм, ГК, отдых',
    'Честь превыше всего',
    'Без паники',
    'За отметками',
    'Каждый бой — как последний',
    'Свои не бросают',
    'Работаем по красным'
  ],
  requirements: [
    'Требования: WN8 от {wn8}, от {battles} боёв, наличие техники X уровня.',
    'Ищем активных игроков: от {battles} боёв, процент побед от {wr}%.',
    'Набор открыт. WN8 от {wn8}, онлайн по вечерам, наличие Discord обязательно.',
    'Принимаем всех адекватных игроков старше 18 лет. Техника от VIII уровня.',
    'Набор закрыт. Заявки рассматриваем только по рекомендации.'
  ],
  activities: [
    'Ежедневно укрепрайоны и вылазки с 19:00 МСК.',
    'Играем турниры, ГК и потасовки. Обучаем новичков.',
    'Взводы на рандоме каждый вечер, по выходным — укрепрайон.',
    'Клановые бои по расписанию, резервы активируем каждый вечер.',
    'Спокойная игра без напряга, взводы и общение.'
  ],
  contacts: ['Связь — в Discord клана.', 'Пишите командиру или офицерам в игре.', 'Заявки через клановый портал.', 'Общение в TeamSpeak и Discord.']
} as const;
