import { z } from 'zod';

export const battleStatsBlockSchema = z.looseObject({
  battles: z.number(),
  wins: z.number(),
  losses: z.number(),
  draws: z.number(),
  xp: z.number(),
  damage_dealt: z.number(),
  damage_received: z.number(),
  frags: z.number(),
  spotted: z.number(),
  capture_points: z.number(),
  dropped_capture_points: z.number(),
  hits: z.number(),
  shots: z.number(),
  survived_battles: z.number(),
  battle_avg_xp: z.number().optional(),
  hits_percents: z.number().optional(),
  piercings: z.number().optional(),
  piercings_received: z.number().optional(),
  explosion_hits: z.number().optional(),
  explosion_hits_received: z.number().optional(),
  direct_hits_received: z.number().optional(),
  no_damage_direct_hits_received: z.number().optional(),
  avg_damage_blocked: z.number().optional(),
  avg_damage_assisted: z.number().optional(),
  avg_damage_assisted_radio: z.number().optional(),
  avg_damage_assisted_track: z.number().optional(),
  avg_damage_assisted_stun: z.number().optional(),
  tanking_factor: z.number().optional(),
  stun_number: z.number().optional(),
  stun_assisted_damage: z.number().optional(),
  max_xp: z.number().optional(),
  max_xp_tank_id: z.number().nullish(),
  max_damage: z.number().optional(),
  max_damage_tank_id: z.number().nullish(),
  max_frags: z.number().optional(),
  max_frags_tank_id: z.number().nullish()
});
