import type { MissionOperationRouteInput, PlayerSessionRouteInput } from './routes.types';

export const ROUTES = {
  home: '/',
  design: '/design',
  players: '/players',
  player: (nickname: string) => `/p/${encodeURIComponent(nickname)}`,
  playerSession: ({ nickname, sessionId }: PlayerSessionRouteInput) => `/p/${encodeURIComponent(nickname)}/sessions/${sessionId}`,
  comparePlayers: '/compare/players',
  me: '/me',
  login: '/login',
  tanks: '/tanks',
  tank: (slug: string) => `/t/${slug}`,
  tankArmor: (slug: string) => `/t/${slug}/armor`,
  compareTanks: '/tanks/compare',
  builds: '/builds',
  build: (slug: string) => `/builds/${slug}`,
  tree: '/tree',
  maps: '/maps',
  map: (id: string) => `/maps/${encodeURIComponent(id)}`,
  guessTank: '/play/guess-tank',
  marks: '/marks',
  missions: '/missions',
  missionOperation: ({ campaign, operation }: MissionOperationRouteInput) => `/missions/${campaign}/${operation}`,
  top: '/top',
  clans: '/clans',
  clan: (tag: string) => `/c/${encodeURIComponent(tag)}`,
  tools: '/tools',
  codes: '/codes',
  news: '/news',
  shop: '/shop',
  events: '/events',
  pulse: '/pulse',
  streamers: '/streamers',
  streamer: (slug: string) => `/s/${encodeURIComponent(slug)}`,
  overlay: (publicId: string) => `/overlay/${encodeURIComponent(publicId)}`,
  developers: '/developers',
  plus: '/plus',
  replays: '/replays',
  replay: (id: string) => `/replays/${encodeURIComponent(id)}`,
  tactics: '/tactics',
  tacticBoard: (id: string) => `/tactics/${encodeURIComponent(id)}`,
  guides: '/guides',
  guide: (slug: string) => `/guides/${encodeURIComponent(slug)}`,
  guideNew: '/guides/new',
  guideEdit: (slug: string) => `/guides/${encodeURIComponent(slug)}/edit`,
  platoons: '/platoons',
  recruiting: '/recruiting',
  coaching: '/coaching',
  coach: (userId: string) => `/coaching/${encodeURIComponent(userId)}`,
  tournaments: '/tournaments',
  tournament: (slug: string) => `/tournaments/${encodeURIComponent(slug)}`,
  loginTelegram: '/login/telegram',
  miniApp: '/tg',
  account: {
    developer: '/me/developer',
    billing: '/me/billing',
    notifications: '/me/notifications',
    telegram: '/me/telegram',
    streamer: '/me/streamer'
  },
  playerCard: (accountId: number) => `/api/og/player/${accountId}`,
  serviceWorker: '/serwist/sw.js'
} as const;
