export {
  AUTHOR_SELECT,
  BUILD_INCLUDE,
  BUILD_SHARE,
  COACHING,
  COMMENTS,
  COMMUNITY_QUEUE,
  COMMUNITY_SCHEDULES,
  GUIDE_INCLUDE,
  GUIDES,
  MODERATION,
  PLATOON,
  RECRUITING,
  TACTICS,
  TOURNAMENT
} from './community.config';
