export { calculateLoadout, computeCrew, CREW, resolveModules, roleFactor, SKILL_EFFECT, VISION } from './loadout';
export type {
  CrewSkillSelection,
  CrewSummary,
  FinalStats,
  InstalledDevice,
  LoadoutCrew,
  LoadoutInput,
  LoadoutState,
  ModulePreset,
  ModuleSelection,
  ShellStats
} from './loadout';
export { CREW_ROLES, NATIONS } from './model';
export type {
  Armor,
  Chassis,
  CrewData,
  CrewMember,
  CrewRole,
  CrewRoleName,
  CrewSkill,
  Currency,
  Engine,
  Equipment,
  EquipmentKind,
  FieldModification,
  FuelTank,
  Gun,
  Hull,
  ModificationPair,
  ModuleBase,
  Nation,
  OptionalDevice,
  OptionalDeviceKind,
  PitchLimits,
  PitchPoint,
  PostProgression,
  Price,
  ProgressionFeature,
  ProgressionStep,
  ProgressionTree,
  Radio,
  RateOfFire,
  Shell,
  Shot,
  SkillBoost,
  SkillParam,
  StepActionType,
  Turret,
  Unlock,
  VehicleClass,
  VehicleFilter,
  VehicleFilterRule,
  VehicleListEntry,
  VehicleProgressionStep,
  VehicleSpec
} from './model';
export { applyModifier, FACTOR_DEFAULTS, matchesDeviceTags, MODIFIER_OPS, STATIC_DEFAULTS } from './modifiers';
export type { DeviceTagFilter, Modifier, ModifierCondition, ModifierOp } from './modifiers';
