export {
  ARMOR_FLAGS,
  ARMOR_GEOMETRY_FORMAT,
  ARMOR_PIECE_KINDS,
  armorFlags,
  armorPieceKind,
  base64ToBytes,
  bytesToBase64,
  calculateArmorHit,
  decodeArmorGeometry,
  encodeArmorGeometry,
  hasArmorFlag,
  isHollowPlate,
  isShieldPlate,
  PENETRATION,
  penetrationAtDistance,
  penetrationVerdict,
  SHELL_KINDS,
  SHELL_RULES,
  toShellKind,
  traceArmorRay
} from './armor';
export type {
  ArmorChassisModule,
  ArmorFlag,
  ArmorGeometry,
  ArmorGroup,
  ArmorGunModule,
  ArmorHit,
  ArmorLayer,
  ArmorModules,
  ArmorMounts,
  ArmorPieceArmor,
  ArmorPieceGeometry,
  ArmorPieceKind,
  ArmorPlate,
  ArmorShell,
  ArmorShellOption,
  ArmorTrace,
  ArmorTraceLayer,
  ArmorTurretModule,
  ArmorVerdict,
  CalculateArmorHitInput,
  PenetrationAtDistanceInput,
  ShellKind,
  TraceArmorRayInput,
  Vec3
} from './armor';
export { calculateLoadout, computeCrew, CREW, resolveModules, roleFactor, SKILL_EFFECT, VISION } from './loadout';
export type {
  CrewSkillSelection,
  CrewSummary,
  FinalStats,
  InstalledDevice,
  LoadoutCrew,
  LoadoutInput,
  LoadoutState,
  ModulePreset,
  ModuleSelection,
  ShellStats
} from './loadout';
export {
  aimCurve,
  aimTime,
  aimTimeline,
  BALLISTICS,
  ballisticsCurve,
  ballisticsDistances,
  camouflageFactor,
  DISPERSION,
  dispersionAfter,
  dispersionFactor,
  effectiveViewRange,
  flightTime,
  FOLIAGE_KINDS,
  HANDLING_SCENARIOS,
  handlingScore,
  penetrationAt,
  scenarioAims,
  scenarioMotion,
  SPOTTING,
  spottingDistance,
  spottingDuel
} from './math';
export type {
  AimCurvePoint,
  BallisticShell,
  BallisticsPoint,
  Camouflage,
  FoliageKind,
  GunHandling,
  HandlingMotion,
  HandlingScenario,
  ScenarioAim,
  SpottingDuel,
  SpottingSide,
  SpottingState,
  SpottingVerdict,
  VisionState
} from './math';
export { CREW_ROLES, NATIONS } from './model';
export type {
  Armor,
  Chassis,
  CrewData,
  CrewMember,
  CrewRole,
  CrewRoleName,
  CrewSkill,
  Currency,
  Engine,
  Equipment,
  EquipmentKind,
  FieldModification,
  FuelTank,
  Gun,
  Hull,
  ModificationPair,
  ModuleBase,
  Nation,
  OptionalDevice,
  OptionalDeviceKind,
  PitchLimits,
  PitchPoint,
  PostProgression,
  Price,
  ProgressionFeature,
  ProgressionStep,
  ProgressionTree,
  Radio,
  RateOfFire,
  Shell,
  Shot,
  SkillBoost,
  SkillParam,
  StepActionType,
  Turret,
  Unlock,
  VehicleClass,
  VehicleFilter,
  VehicleFilterRule,
  VehicleListEntry,
  VehicleProgressionStep,
  VehicleSpec
} from './model';
export { applyModifier, FACTOR_DEFAULTS, matchesDeviceTags, MODIFIER_OPS, STATIC_DEFAULTS } from './modifiers';
export type { DeviceTagFilter, Modifier, ModifierCondition, ModifierOp } from './modifiers';
