from __future__ import absolute_import, division, print_function, unicode_literals

from ...core.hud.modifier import DEFAULT_MODIFIER, MODIFIER_CHOICES

DEFAULT_SERVER_URL = 'https://api.triotmetki.ru'
FEATURES = (
    'send_battle_results',
    'send_moe_snapshots',
    'send_queue_times',
    'send_loadouts',
    'send_shots',
    'battle_moe_panel',
    'hangar_session_panel',
    'battle_damage_log',
    'battle_hit_log',
    'battle_clock',
    'battle_team_hp',
    'battle_sixth_sense',
    'hangar_battle_results',
    'hangar_replay_manager',
    'hangar_tweaks',
    'minimap_tweaks',
    'camera_tweaks',
    'crosshair_presets',
    'hangar_info',
    'battle_sounds',
    'battle_chat_filter',
    'hangar_auto_resupply',
    'hangar_notification_filter',
    'hangar_cleaner',
    'hangar_marks_history',
    'hangar_ratings',
    'hangar_marks',
    'battle_personal_best',
    'hangar_session_goals',
    'battle_main_gun',
    'battle_efficiency',
    'battle_consumables',
    'battle_reload_timer',
    'battle_received_hits',
    'battle_death_card',
    'battle_loadout',
    'hangar_personal_missions',
    'streamer_mode',
    'hangar_platoon_helper',
    'hangar_tilt_guard',
    'hangar_battle_hits',
    'battle_gun_arc',
    'battle_bush_circle',
    'battle_arty_meter',
    'battle_platoon_points',
    'battle_hud_layouts',
    'hangar_comp7_helper',
    'hangar_event_trackers',
    'share_settings',
    'upload_replays',
    'publish_replays',
    'share_session_report',
)
# Off until the player turns them on: the uploads (privacy) and the secondary battle panels, so a default
# battle shows only the essentials (team HP, damage and hit logs, marks, the reload timer, the equipment over
# the stock consumables panel, the sixth sense lamp, the death card). The consumables bar repeats the stock
# panel and is opt-in too.
OPT_IN_FEATURES = (
    'upload_replays',
    'publish_replays',
    'share_session_report',
    'battle_main_gun',
    'battle_efficiency',
    'battle_personal_best',
    'battle_gun_arc',
    'battle_arty_meter',
    'battle_platoon_points',
    'battle_received_hits',
    'battle_consumables',
    'battle_clock',
    'hangar_event_trackers',
)
SHARE_CHANNELS = ('telegram', 'discord', 'both')
# config.json keeps every default it was written with: a switch whose default changed is moved to the new
# one when it still holds the old default and the file predates the change (`defaults_revision`).
# (revision, key, old default, new default).
DEFAULTS_REVISION = 1
RETIRED_DEFAULTS = (
    (1, 'battle_consumables', True, False),
    (1, 'battle_loadout', False, True),
)
DEFAULTS = {
    'enabled': True,
    'server_url': DEFAULT_SERVER_URL,
    'language': 'auto',
    'session_idle_minutes': 60,
    'flush_interval_seconds': 15,
    'bind_code': '',
    'send_battle_results': True,
    'send_moe_snapshots': True,
    'send_queue_times': True,
    'send_loadouts': True,
    'send_shots': True,
    'battle_moe_panel': True,
    'hangar_session_panel': True,
    'battle_damage_log': True,
    'battle_hit_log': True,
    'battle_clock': False,
    'battle_team_hp': True,
    'battle_sixth_sense': True,
    'hangar_battle_results': True,
    'hangar_replay_manager': True,
    'hangar_tweaks': True,
    'minimap_tweaks': True,
    'camera_tweaks': True,
    'crosshair_presets': True,
    'hangar_info': True,
    'battle_sounds': True,
    'battle_chat_filter': True,
    'hangar_auto_resupply': True,
    'hangar_notification_filter': True,
    'hangar_cleaner': True,
    'hangar_marks_history': True,
    'hangar_ratings': True,
    'hangar_marks': True,
    'battle_personal_best': False,
    'hangar_session_goals': True,
    'battle_main_gun': False,
    'battle_efficiency': False,
    'battle_consumables': False,
    'battle_reload_timer': True,
    'battle_received_hits': False,
    'battle_death_card': True,
    'battle_loadout': True,
    'hangar_personal_missions': True,
    'streamer_mode': True,
    'hangar_platoon_helper': True,
    'hangar_tilt_guard': True,
    'hangar_battle_hits': True,
    'battle_gun_arc': False,
    'battle_bush_circle': True,
    'battle_arty_meter': False,
    'battle_platoon_points': False,
    'battle_hud_layouts': True,
    'hangar_comp7_helper': True,
    'hangar_event_trackers': False,
    'share_settings': True,
    'upload_replays': False,
    'publish_replays': False,
    'share_session_report': False,
    'share_session_channel': 'telegram',
    'settings_action': '',
    'settings_target': 'private',
    'settings_anonymous_stats': False,
    'settings_include_resolution': False,
    'settings_include_sensitivity': False,
    'hud_modifier': DEFAULT_MODIFIER,
    'defaults_revision': DEFAULTS_REVISION,
}
CHOICES = {
    'settings_action': ('', 'export', 'restore'),
    'settings_target': ('profile', 'private'),
    'share_session_channel': SHARE_CHANNELS,
    'hud_modifier': MODIFIER_CHOICES,
}
LIMITS = {
    'session_idle_minutes': (10, 24 * 60),
    'flush_interval_seconds': (5, 600),
}
LOCAL_HOSTS = ('http://localhost', 'http://127.0.0.1')
