from __future__ import absolute_import, division, print_function, unicode_literals

from ...core.hud.modifier import DEFAULT_MODIFIER, MODIFIER_CHOICES

DEFAULT_SERVER_URL = 'https://api.triotmetki.ru'
FEATURES = (
    'send_battle_results',
    'send_moe_snapshots',
    'send_queue_times',
    'send_loadouts',
    'send_shots',
    'battle_moe_panel',
    'hangar_session_panel',
    'battle_damage_log',
    'battle_hit_log',
    'battle_clock',
    'battle_team_hp',
    'battle_sixth_sense',
    'hangar_battle_results',
    'hangar_replay_manager',
    'hangar_tweaks',
    'minimap_tweaks',
    'camera_tweaks',
    'crosshair_presets',
    'hangar_info',
    'battle_sounds',
    'battle_chat_filter',
    'hangar_auto_resupply',
    'hangar_notification_filter',
    'hangar_cleaner',
    'hangar_marks_history',
    'hangar_ratings',
    'hangar_marks',
    'battle_personal_best',
    'hangar_session_goals',
    'battle_main_gun',
    'battle_efficiency',
    'battle_consumables',
    'battle_reload_timer',
    'battle_received_hits',
    'battle_death_card',
    'battle_loadout',
    'hangar_personal_missions',
    'streamer_mode',
    'hangar_platoon_helper',
    'hangar_tilt_guard',
    'hangar_battle_hits',
    'battle_gun_arc',
    'battle_bush_circle',
    'share_settings',
    'upload_replays',
    'publish_replays',
    'share_session_report',
)
OPT_IN_FEATURES = ('upload_replays', 'publish_replays', 'share_session_report')
SHARE_CHANNELS = ('telegram', 'discord', 'both')
DEFAULTS = {
    'enabled': True,
    'server_url': DEFAULT_SERVER_URL,
    'language': 'auto',
    'session_idle_minutes': 60,
    'flush_interval_seconds': 15,
    'bind_code': '',
    'send_battle_results': True,
    'send_moe_snapshots': True,
    'send_queue_times': True,
    'send_loadouts': True,
    'send_shots': True,
    'battle_moe_panel': True,
    'hangar_session_panel': True,
    'battle_damage_log': True,
    'battle_hit_log': True,
    'battle_clock': True,
    'battle_team_hp': True,
    'battle_sixth_sense': True,
    'hangar_battle_results': True,
    'hangar_replay_manager': True,
    'hangar_tweaks': True,
    'minimap_tweaks': True,
    'camera_tweaks': True,
    'crosshair_presets': True,
    'hangar_info': True,
    'battle_sounds': True,
    'battle_chat_filter': True,
    'hangar_auto_resupply': True,
    'hangar_notification_filter': True,
    'hangar_cleaner': True,
    'hangar_marks_history': True,
    'hangar_ratings': True,
    'hangar_marks': True,
    'battle_personal_best': True,
    'hangar_session_goals': True,
    'battle_main_gun': True,
    'battle_efficiency': True,
    'battle_consumables': True,
    'battle_reload_timer': True,
    'battle_received_hits': True,
    'battle_death_card': True,
    'battle_loadout': True,
    'hangar_personal_missions': True,
    'streamer_mode': True,
    'hangar_platoon_helper': True,
    'hangar_tilt_guard': True,
    'hangar_battle_hits': True,
    'battle_gun_arc': True,
    'battle_bush_circle': True,
    'share_settings': True,
    'upload_replays': False,
    'publish_replays': False,
    'share_session_report': False,
    'share_session_channel': 'telegram',
    'settings_action': '',
    'settings_target': 'private',
    'settings_anonymous_stats': False,
    'settings_include_resolution': False,
    'settings_include_sensitivity': False,
    'hud_modifier': DEFAULT_MODIFIER,
}
CHOICES = {
    'settings_action': ('', 'export', 'restore'),
    'settings_target': ('profile', 'private'),
    'share_session_channel': SHARE_CHANNELS,
    'hud_modifier': MODIFIER_CHOICES,
}
LIMITS = {
    'session_idle_minutes': (10, 24 * 60),
    'flush_interval_seconds': (5, 600),
}
LOCAL_HOSTS = ('http://localhost', 'http://127.0.0.1')
