export { ARMOR_LAYERS } from './config';
export { describeHit } from './lib/hit-report';
export type { HitLayer, HitReport } from './lib/hit-report';
export { useArmorAttack, useArmorInspect } from './model/context';
export type { ArmorLayerKey } from './model/context';
export { ArmorAttackProvider } from './ui/ArmorAttackProvider';
export { ArmorInspectPanel } from './ui/ArmorInspectPanel';
export { ArmorInspectProvider } from './ui/ArmorInspectProvider';
export { HitReadout } from './ui/HitReadout';
export { ModulePicker } from './ui/ModulePicker';
