export { changeBaseline, changeVerdict } from './change-verdict';
export type { ChangeVerdict } from './change-verdict';
export { devChanges, devNewVehicleChanges } from './dev-changes';
export { liveValue } from './live-value';
export { paramMeta, paramOf, parsedUnit } from './param-key';
export type { SupertestParamKey, SupertestParamMeta } from './param-key';
export { parseParamLine, parseValueCell } from './param-line';
export { NUMBER_SOURCE, parseRussianNumber } from './russian-number';
export { isSupertestTitle, parseSupertestArticle } from './supertest-article';
export type { ParsedChange, ParsedTank } from './supertest-article';
export { narrowToTanks, supertestTotals, tankVerdict } from './supertest-summary';
