export { getArmorModel } from './api';
export type { ArmorModelInput } from './api';
export { ARMOR_FACE_CLASSES, ARMOR_PALETTE } from './config';
export { ARMOR_SHADER, armorShaderValues } from './lib/armor-shader';
export type { ArmorShaderInput, ArmorShaderValues } from './lib/armor-shader';
export { buildPieceBuffers } from './lib/build-buffers';
export type { PieceBuffers } from './lib/build-buffers';
export { classifyFace } from './lib/classify-face';
export { decodeArmorModel } from './lib/decode-model';
export type { ArmorFaceClass, ArmorModelData, ArmorShellState } from './model/armor-model.types';
export { useArmorModel } from './model/hooks';
